In [1]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [2]:
import bokeh as bk
bk.sampledata.download()

Using data directory: C:\Users\GamaPSH\.bokeh\data
Skipping 'CGM.csv' (checksum match)
Skipping 'US_Counties.zip' (checksum match)
Skipping 'us_cities.json' (checksum match)
Skipping 'unemployment09.csv' (checksum match)
Skipping 'AAPL.csv' (checksum match)
Skipping 'FB.csv' (checksum match)
Skipping 'GOOG.csv' (checksum match)
Skipping 'IBM.csv' (checksum match)
Skipping 'MSFT.csv' (checksum match)
Skipping 'WPP2012_SA_DB03_POPULATION_QUINQUENNIAL.zip' (checksum match)
Skipping 'gapminder_fertility.csv' (checksum match)
Skipping 'gapminder_population.csv' (checksum match)
Skipping 'gapminder_life_expectancy.csv' (checksum match)
Skipping 'gapminder_regions.csv' (checksum match)
Skipping 'world_cities.zip' (checksum match)
Skipping 'airports.json' (checksum match)
Skipping 'movies.db.zip' (checksum match)
Skipping 'airports.csv' (checksum match)
Skipping 'routes.csv' (checksum match)
Skipping 'haarcascade_frontalface_default.xml' (checksum match)

In [3]:
from bokeh.sampledata.autompg import autompg

In [4]:
df = autompg

In [5]:
df

,mpg,cyl,displ,hp,weight,accel,yr,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

ASSGN - 1

In [6]:
def plot(df):
    from bokeh.io import output_file, show
    from bokeh.models import ColumnDataSource
    from bokeh.palettes import Spectral6
    from bokeh.plotting import figure,output_notebook
    from bokeh.transform import factor_cmap

    output_notebook()

    Attributes = df.columns.values
    counts = df.iloc[0].values

    source = ColumnDataSource(data=dict(Attributes=Attributes, counts=counts))

    p = figure(x_range=Attributes, plot_height=650, toolbar_location=None, title="Attribute Counts")
    p.vbar(x='Attributes', top='counts', width=0.9, source=source, legend_field="Attributes",
           line_color='white', fill_color=factor_cmap('Attributes', palette=Spectral6, factors=Attributes))

    p.xgrid.grid_line_color = None
    p.y_range.start = 0
    p.y_range.end = 500
    p.legend.orientation = "horizontal"
    p.legend.location = "top_center"

    show(p)

In [7]:
def classify(val):
    df['rating'] = 'None'
    print(val)
    if isinstance(val, str) :
        raise ValueError("you were not allowed to have string in val!") 
    else:
        df['rating'] = val
        plot(df)

ASSGN - 2

In [8]:
covid19_dict = {
    'Country' : ['USA','China','Italy','Spain'],
    'Cases' : [141559,97689,81439,80110],
    'Recovered': ['4,435','13,030','75,448','14,709'],
}

In [9]:
data_covid = pd.DataFrame(data = covid19_dict)

In [10]:
data_covid

  Country   Cases Recovered
0     USA  141559     4,435
1   China   97689    13,030
2   Italy   81439    75,448
3   Spain   80110    14,709

In [11]:
req = data_covid[['Country','Cases']]

In [12]:
req.rename(columns={'Cases':'value','Country':'country'})

  country   value
0     USA  141559
1   China   97689
2   Italy   81439
3   Spain   80110

In [13]:
def plot(req):
    from math import pi
    from bokeh.io import output_file, show
    from bokeh.palettes import Category20c
    from bokeh.plotting import figure, output_notebook
    from bokeh.transform import cumsum
    
    output_notebook()
    x = req
    print(x)


    data = req.rename(columns={'Cases':'value','Country':'country'})
    data['angle'] = data['value']/data['value'].sum() * 2*pi
    data['color'] = Category20c[len(x)]

    p = figure(plot_height=350, title="Pie Chart", toolbar_location=None,
               tools="hover", tooltips="@country: @value", x_range=(-0.5, 1.0))

    p.wedge(x=0, y=1, radius=0.4,
            start_angle=cumsum('angle', include_zero=True), end_angle=cumsum('angle'),
            line_color="white", fill_color='color', legend_field='country', source=data)

    p.axis.axis_label=None
    p.axis.visible=False
    p.grid.grid_line_color = None

    show(p)

In [14]:
plot(req)

  Country   Cases
0     USA  141559
1   China   97689
2   Italy   81439
3   Spain   80110

ASSGN - 3

In [15]:
import bokeh
bokeh.sampledata.download() 
from bokeh.sampledata.autompg import autompg

Using data directory: C:\Users\GamaPSH\.bokeh\data
Skipping 'CGM.csv' (checksum match)
Skipping 'US_Counties.zip' (checksum match)
Skipping 'us_cities.json' (checksum match)
Skipping 'unemployment09.csv' (checksum match)
Skipping 'AAPL.csv' (checksum match)
Skipping 'FB.csv' (checksum match)
Skipping 'GOOG.csv' (checksum match)
Skipping 'IBM.csv' (checksum match)
Skipping 'MSFT.csv' (checksum match)
Skipping 'WPP2012_SA_DB03_POPULATION_QUINQUENNIAL.zip' (checksum match)
Skipping 'gapminder_fertility.csv' (checksum match)
Skipping 'gapminder_population.csv' (checksum match)
Skipping 'gapminder_life_expectancy.csv' (checksum match)
Skipping 'gapminder_regions.csv' (checksum match)
Skipping 'world_cities.zip' (checksum match)
Skipping 'airports.json' (checksum match)
Skipping 'movies.db.zip' (checksum match)
Skipping 'airports.csv' (checksum match)
Skipping 'routes.csv' (checksum match)
Skipping 'haarcascade_frontalface_default.xml' (checksum match)

In [16]:
df = autompg

In [17]:
df

,mpg,cyl,displ,hp,weight,accel,yr,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
387,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
388,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
389,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
390,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
391,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [18]:
df.loc[1,'name']

'buick skylark 320'

In [19]:
n_df = df.head(50)

In [20]:
n_df['company'] = 'Blank'

In [21]:
my_company = ['chevrolet','amc','buick','plymouth','ford','dodge']
def add_column(row):
    #print(name, row['name'])
    if name in row['name']:
        return name
    else:
        return row['company']

In [22]:
def add_company_name(name,n_df):
    for index,row in n_df.iterrows():
        n_df.loc[index,'company'] = add_column(row)
    return n_df

In [23]:
for name in my_company:
     add_company_name(name,n_df)

In [24]:
n_df

,mpg,cyl,displ,hp,weight,accel,yr,origin,name,company
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu,chevrolet
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320,buick
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite,plymouth
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst,amc
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino,ford
5,15.0,8,429.0,198,4341,10.0,70,1,ford galaxie 500,ford
6,14.0,8,454.0,220,4354,9.0,70,1,chevrolet impala,chevrolet
7,14.0,8,440.0,215,4312,8.5,70,1,plymouth fury iii,plymouth
8,14.0,8,455.0,225,4425,10.0,70,1,pontiac catalina,Blank
9,15.0,8,390.0,190,3850,8.5,70,1,amc ambassador dpl,amc
10,15.0,8,383.0,170,3563,10.0,70,1,dodge challenger se,dodge
11,14.0,8,340.0,160,3609,8.0,70,1,plymouth 'cuda 340,plymouth
12,15.0,8,400.0,150,3761,9.5,70,1,chevrolet monte carlo,chevrolet
13,14.0,8,455.0,225,3086,10.0,70,1,buick estate wagon (sw),buick
14,24.0,4,113.0,95,2372,15.0,70,3,toyota corona mark ii,Blank
15,22.0,6,198.0,95,2833,15.5,70,1,plymouth duster,plymouth
16,18.0,6,199.0,97,2774,15.5,70,1,amc hornet,amc
17,21.0,6,200.0,85,2587,16.0,70,1,ford maverick,ford
18,27.0,4,97.0,88,2130,14.5,70,3,datsun pl510,Blank
19,26.0,4,97.0,46,1835,20.5,70,2,volkswagen 1131 deluxe sedan,Blank
20,25.0,4,110.0,87,2672,17.5,70,2,peugeot 504,Blank
21,24.0,4,107.0,90,2430,14.5,70,2,audi 100 ls,Blank
22,25.0,4,104.0,95,2375,17.5,70,2,saab 99e,Blank
23,26.0,4,121.0,113,2234,12.5,70,2,bmw 2002,Blank
24,21.0,6,199.0,90,2648,15.0,70,1,amc gremlin,amc
25,10.0,8,360.0,215,4615,14.0,70,1,ford f250,ford
26,10.0,8,307.0,200,4376,15.0,70,1,chevy c20,Blank
27,11.0,8,318.0,210,4382,13.5,70,1,dodge d200,dodge
28,9.0,8,304.0,193,4732,18.5,70,1,hi 1200d,Blank
29,27.0,4,97.0,88,2130,14.5,71,3,datsun pl510,Blank
30,28.0,4,140.0,90,2264,15.5,71,1,chevrolet vega 2300,chevrolet
31,25.0,4,113.0,95,2228,14.0,71,3,toyota corona,Blank
32,19.0,6,232.0,100,2634,13.0,71,1,amc gremlin,amc
33,16.0,6,225.0,105,3439,15.5,71,1,plymouth satellite custom,plymouth
34,17.0,6,250.0,100,3329,15.5,71,1,chevrolet chevelle malibu,chevrolet
35,19.0,6,250.0,88,3302,15.5,71,1,ford torino 500,ford
36,18.0,6,232.0,100,3288,15.5,71,1,amc matador,amc
37,14.0,8,350.0,165,4209,12.0,71,1,chevrolet impala,chevrolet
38,14.0,8,400.0,175,4464,11.5,71,1,pontiac catalina brougham,Blank
39,14.0,8,351.0,153,4154,13.5,71,1,ford galaxie 500,ford
40,14.0,8,318.0,150,4096,13.0,71,1,plymouth fury iii,plymouth
41,12.0,8,383.0,180,4955,11.5,71,1,dodge monaco (sw),dodge
42,13.0,8,400.0,170,4746,12.0,71,1,ford country squire (sw),ford
43,13.0,8,400.0,175,5140,12.0,71,1,pontiac safari (sw),Blank
44,18.0,6,258.0,110,2962,13.5,71,1,amc hornet sportabout (sw),amc
45,22.0,4,140.0,72,2408,19.0,71,1,chevrolet vega (sw),chevrolet
46,19.0,6,250.0,100,3282,15.0,71,1,pontiac firebird,Blank
47,18.0,6,250.0,88,3139,14.5,71,1,ford mustang,ford
48,23.0,4,122.0,86,2220,14.0,71,1,mercury capri 2000,Blank
49,28.0,4,116.0,90,2123,14.0,71,2,opel 1900,Blank

In [25]:
g = n_df.groupby(['company'])

In [26]:
grps =g.groups

In [27]:
grps

{'Blank': Int64Index([8, 14, 18, 19, 20, 21, 22, 23, 26, 28, 29, 31, 38, 43, 46, 48, 49], dtype='int64'),
 'amc': Int64Index([3, 9, 16, 24, 32, 36, 44], dtype='int64'),
 'buick': Int64Index([1, 13], dtype='int64'),
 'chevrolet': Int64Index([0, 6, 12, 30, 34, 37, 45], dtype='int64'),
 'dodge': Int64Index([10, 27, 41], dtype='int64'),
 'ford': Int64Index([4, 5, 17, 25, 35, 39, 42, 47], dtype='int64'),
 'plymouth': Int64Index([2, 7, 11, 15, 33, 40], dtype='int64')}